In [1]:
import numpy as np

## np.loadtxt() vs np.genfromtxt()

In [2]:
filename = "C:/Users/m.pirela.escobar/OneDrive - Accenture/Documents/Courses/Data_Analyst/Data Analyst Course/S10 - Working with Text Files/L15/Lending-Company-Numeric-Data.csv"
leading_co_data_numeric_1 = np.loadtxt(filename, delimiter = ',')
leading_co_data_numeric_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [3]:
# ahora usando genfromtxt()

In [4]:
filename = "C:/Users/m.pirela.escobar/OneDrive - Accenture/Documents/Courses/Data_Analyst/Data Analyst Course/S10 - Working with Text Files/L15/Lending-Company-Numeric-Data.csv"
leading_co_data_numeric_2 = np.genfromtxt(filename, delimiter = ',')
leading_co_data_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [5]:
# Para saber si son iguales los arrays generados
np.array_equal(leading_co_data_numeric_1, leading_co_data_numeric_2)

True

In [6]:
# Sabiendo que el método genfromtxt es mejor para manejar valores nulos

filename = "C:/Users/m.pirela.escobar/OneDrive - Accenture/Documents/Courses/Data_Analyst/Data Analyst Course/S10 - Working with Text Files/L15/Lending-Company-Numeric-Data-NAN.csv"
leading_co_data_numeric_NAN = np.loadtxt(filename, delimiter = ';')
leading_co_data_numeric_NAN

ValueError: could not convert string to float: ''

In [7]:
# Como tiene valores nulos entonces usamos genfromtxt
filename = "C:/Users/m.pirela.escobar/OneDrive - Accenture/Documents/Courses/Data_Analyst/Data Analyst Course/S10 - Working with Text Files/L15/Lending-Company-Numeric-Data-NAN.csv"
leading_co_data_numeric_NAN = np.genfromtxt(filename, delimiter = ';')
leading_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [8]:
leading_co_data_numeric_NAN = np.genfromtxt(filename, delimiter = ';', skip_header = 2)
leading_co_data_numeric_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [10]:
leading_co_data_numeric_NAN = np.genfromtxt(filename, delimiter = ';', skip_footer = 2)
leading_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [14]:
leading_co_data_numeric_NAN = np.genfromtxt(filename, delimiter = ';', usecols = (5,0,1))
leading_co_data_numeric_NAN

array([[13621.,  2000.,    40.],
       [15041.,  2000.,    40.],
       [15340.,  1000.,    40.],
       ...,
       [16600.,    nan,    40.],
       [15600.,  1000.,    40.],
       [16600.,  2000.,    40.]])

In [16]:
leading_co_data_numeric_NAN = np.genfromtxt(filename, delimiter = ';', usecols = (5,0,1),
                                                                                   skip_header = 2, skip_footer = 2)
leading_co_data_numeric_NAN

array([[15340.,  1000.,    40.],
       [15321.,  2000.,    40.],
       [13720.,  2000.,    50.],
       ...,
       [16600.,  2000.,    40.],
       [16600.,  2000.,    40.],
       [16600.,    nan,    40.]])

In [17]:
# para seleccionar varias columnas a la vez y convertirlas individualmente se puede usar la forma de Python para Tuples
leading_co_data_5, leading_co_data_0, leading_co_data_1, = np.genfromtxt(filename, delimiter = ';', usecols = (5,0,1), 
                                                                        skip_header = 2, skip_footer= 2, unpack = True)

print(leading_co_data_5)
print(leading_co_data_0)
print(leading_co_data_1)

[15340. 15321. 13720. ... 16600. 16600. 16600.]
[1000. 2000. 2000. ... 2000. 2000.   nan]
[40. 40. 50. ... 40. 40. 40.]
