In [ ]:
import math

In [ ]:
math.sqrt(16)

In [ ]:
from math import sqrt

In [ ]:
sqrt(25)

## Numpy

In [3]:
import numpy as np

In [2]:
np.__version__

'1.22.3'

In [3]:
import pandas as pd

In [4]:
pd.__version__

'1.4.2'

## Linear Algebra

In [5]:
import numpy as np

## Scalars

In [6]:
S  = 5
S

5

## vECTOR

In [7]:
v = np.array([5,5,-4])

In [8]:
v

array([ 5,  5, -4])

## Matrices

In [10]:
m = np.array([[5,12,6], [-3,0,14])

In [12]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [15]:
type(S)

int

In [16]:
type(v)

numpy.ndarray

In [17]:
type(m)

numpy.ndarray

In [18]:
s_array = np.array(5)
s_array

array(5)

In [19]:
type(s_array)

numpy.ndarray

 ## Data shapes

In [20]:
m.shape

(2, 3)

In [21]:
v.shape

(3,)

In [24]:
s_array.shape

()

## Creating a Tensor

In [25]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [27]:
m2 = np.array([[9,8,7], [1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [30]:
t = np.array([m1,m2])

In [31]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [32]:
t.shape

(2, 2, 3)

## Addition

In [4]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [5]:
m2 = np.array([[9,8,7], [1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [6]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

## Difference

In [8]:
m3 = np.array([[5,3], [-2,4]])
m4 = np.array([[7, -5], [3,8]])

In [9]:
m3 - m4

array([[-2,  8],
       [-5, -4]])

In [13]:
m5 = np.array([[22.33, -4.73], [-203.14, 1200.02], [4.22, 234.1]])
m6 = np.array([[131.13, 448.29], [-340.21, 1.06],[30.41, 424.99]])

In [14]:
m5 - m6

array([[-108.8 , -453.02],
       [ 137.07, 1198.96],
       [ -26.19, -190.89]])

## Adding vectors together

In [23]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([list(range(1,6))[::-1]])

In [24]:
v1 + v2

array([[6, 6, 6, 6, 6]])

In [25]:
v1 - v2

array([[-4, -2,  0,  2,  4]])

## Scalar

## Addition

In [26]:
5 + 5

10

In [27]:
10 - 4

6

## Transposing matrices

In [28]:
A = np.array([[5,12,6], [-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [29]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [30]:
B = np.array([[5,3], [-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [31]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [33]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [34]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

## Dot Product

In [35]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [36]:
np.dot(x,y)

-66

In [37]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [38]:
np.dot(u,v)

18

## Scalar * Vector

In [39]:
x 

array([ 2,  8, -4])

In [40]:
5*x

array([ 10,  40, -20])

## Dot product on Matrices

In [41]:
A = np.array([[5,12,6], [-3,0,14]])

In [42]:
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [43]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

### Matrix x Matrix

In [44]:
B = np.array([[2,-1], [8,0], [3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [45]:
np.dot(A,B)

array([[124,  -5],
       [ 36,   3]])

## Numpy Basics

In [2]:
import numpy as np

In [3]:
array_a = np.array([1,2,3])

In [4]:
array_a

array([1, 2, 3])

In [5]:
array_a.shape

(3,)

In [6]:
array_a.reshape

<function ndarray.reshape>

In [7]:
array_a.shape

(3,)

In [9]:
array_b = np.array([[1,2,3], [4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

## Pandas

In [10]:
import pandas as pd

In [11]:
products = ['A','B', 'C', 'D' ]
products

['A', 'B', 'C', 'D']

In [12]:
type(products)

list

In [13]:
products_category = pd.Series(products)

In [14]:
products_category

0    A
1    B
2    C
3    D
dtype: object

In [15]:
type(products_category)

pandas.core.series.Series

In [16]:
type(pd.Series(products_category))

pandas.core.series.Series

In [17]:
daily_rates_dollars = pd.Series([40,45,50,60]) 
daily_rates_dollars

0    40
1    45
2    50
3    60
dtype: int64

In [19]:
print(daily_rates_dollars)

0    40
1    45
2    50
3    60
dtype: int64


In [20]:
import numpy as np

In [22]:
array_a = np.array([10,20,30,40,50])

In [23]:
type(array_a)

numpy.ndarray

### Para convertir np.array a un pd.Series

In [24]:
series_a = pd.Series(array_a)
series_a

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [25]:
print(series_a)

0    10
1    20
2    30
3    40
4    50
dtype: int32


In [26]:
type(series_a)

pandas.core.series.Series

## Using an Index in pandas

In [27]:
prices_per_category = {'Product A': 22250, 'Product B': 16600, 'Product C': 15600}
prices_per_category

{'Product A': 22250, 'Product B': 16600, 'Product C': 15600}

In [28]:
type(prices_per_category)

dict

In [29]:
prices_per_category = pd.Series(prices_per_category)
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [30]:
type(prices_per_category)

pandas.core.series.Series

In [31]:
prices_per_category.index

Index(['Product A', 'Product B', 'Product C'], dtype='object')

In [32]:
type(prices_per_category.index)

pandas.core.indexes.base.Index

## Index

In [33]:
series_a = pd.Series([10,20,30,40,50])
series_a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [34]:
 series_a.index

RangeIndex(start=0, stop=5, step=1)

In [35]:
type(series_a.index)

pandas.core.indexes.range.RangeIndex

In [36]:
series_a = pd.Series([10,20,30,40,50])
prices_per_category = pd.Series(prices_per_category)

In [37]:
series_a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [38]:
series_a[0]

10

In [39]:
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [41]:
prices_per_category['Product A']

22250

In [43]:
prices_per_category[0]

22250

In [44]:
series_b = pd.Series([10,20,30,40,50], index = [1,2,3,4,5])
series_b

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [45]:
series_b[0]

KeyError: 0

In [46]:
series_b[1]

10

In [47]:
series_c = pd.Series([10,20,30,40,50], index = ["1", "2", "3", "4", "5"])
series_c

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [48]:
series_c[1]

20

In [49]:
series_c["1"]

10

In [1]:
import pandas as pd

In [2]:
start_date_deposits = pd.Series({
    '7/4/2014' : 2000,
    '1/2/2015' : 2000,
    '12/8/2012' : 1000,
    '2/20/2015' : 2000,
    '10/28/2013' : 2000,
    '4/19/2015' : 2000,
    '7/4/2016' : 2000,
    '4/24/2014' : 2000,
    '9/3/2015' : 4000,
    '7/25/2016' : 2000,
    '5/1/2014' : 2000,
    '3/29/2013' : 2000,
    '10/3/2014' : 2000,
    '9/18/2015' : 2500
})

In [4]:
start_date_deposits

7/4/2014      2000
1/2/2015      2000
12/8/2012     1000
2/20/2015     2000
10/28/2013    2000
4/19/2015     2000
7/4/2016      2000
4/24/2014     2000
9/3/2015      4000
7/25/2016     2000
5/1/2014      2000
3/29/2013     2000
10/3/2014     2000
9/18/2015     2500
dtype: int64

In [6]:
start_date_deposits.sum()

29500

In [7]:
start_date_deposits.min()

1000

In [8]:
start_date_deposits.idxmax()

'9/3/2015'

In [10]:
start_date_deposits.idxmin()

'12/8/2012'

In [11]:
start_date_deposits.head()

7/4/2014      2000
1/2/2015      2000
12/8/2012     1000
2/20/2015     2000
10/28/2013    2000
dtype: int64

## Pandas DataFrames

### Creating DataFrames from Scratch

#### Creating a DataFrame from a Dictionary

In [12]:
data = {'ProductName': ['Product A', 'Product B', 'Product C'], 'ProductPrice': [22250, 16600, 12500]}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0   Product A         22250
1   Prodcut B         16600
2   Product C         12500

In [13]:
# PAra colocar los índices

In [15]:
data = {'ProductName':  ['Product A', 'Product B', 'Product C'], 'ProductPrice':  [22250, 16600, 12500]}
df = pd.DataFrame(data, index = ['A', 'B', 'C'])
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

In [16]:
# También podemos pasar los índices como una variable
data = {'ProductName':  ['Product A', 'Product B', 'Product C'], 'ProductPrice':  [22250, 16600, 12500]}
products_IDs = ['A', 'B', 'C']
df = pd.DataFrame(data, index = products_IDs)
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

### Construct a DataFrame from a dictionary of pandas Series

In [19]:
ser_products = pd.Series(['Product A', 'Product B', 'Product C'])
ser_prices = pd.Series([22250, 16600, 12500])
df = pd.DataFrame({'ProductName':ser_products, 'ProductPrice': ser_prices})
df

ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500

In [20]:
# Adding index
ser_products = pd.Series(['Product A', 'Product B', 'Product C'], index = ['A', 'B', 'C'])
ser_prices = pd.Series([22250, 16600, 12500], index = ['A', 'B', 'C'])
df = pd.DataFrame({'ProductName':ser_products, 'ProductPrice': ser_prices})
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

In [22]:
# From a list of list
data = [['Product A', 22250], ['Product B', 16600], ['Product C', 12500]]
df = pd.DataFrame(data)
df

0      1
0  Product A  22250
1  Product B  16600
2  Product C  12500

In [24]:
df.columns = ['ProductName', 'ProductPrice']
df

ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500

In [25]:
df.index = ['A', 'B', 'C']
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

In [29]:
df = pd.DataFrame(data = [['Product A', 22250] , ['Product B', 16600] , ['Product C', 12500]],
                                 columns = (['ProductName', 'ProductPrice']),
                                 index = ['A', 'B', 'C'])
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

In [30]:
df.shape

(3, 2)